## Home Work One - 2025 ML Zoomcamp by Norman Angel
## Date: Sept 16, 2025

In [63]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [9]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

#### Q1. Pandas version
What's the version of Pandas that you installed?



In [10]:
pd.__version__

'2.3.1'

#### Q2. Records count
How many records are in the dataset?

In [59]:
df.shape

(9704, 11)

#### Q3. Fuel types
How many fuel types are presented in the dataset?


In [14]:
df['fuel_type'].nunique()


2

#### Q4. Missing values
How many columns in the dataset have missing values?

In [23]:
# List all coulmns with true or false for Null values

df.isna().any()


engine_displacement    False
num_cylinders           True
horsepower              True
vehicle_weight         False
acceleration            True
model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors               True
fuel_efficiency_mpg    False
dtype: bool

In [24]:
# L:ist only columns with missing values

df.columns[df.isna().any()].tolist()

['num_cylinders', 'horsepower', 'acceleration', 'num_doors']

In [25]:
# Count of missing values per fcolumn

df.isna().sum()[df.isna().sum() > 0]


num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

#### Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [62]:
# Sellecting cars from Asia
df_as = df[df['origin'] == 'Asia']

# Find the max fuel effiecny for cars from Asia
df_as['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

#### Q6. Median value of horsepower

Find the median value of horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.
Has it changed?

Yes, it increased
Yes, it decreased
No

In [35]:
# FInd Median

median_before = df['horsepower'].median()
print("Median before filling missing values:", median_before)

Median before filling missing values: 149.0


In [36]:
## Find Mode
mode_value = df['horsepower'].mode()[0]  # mode() returns a Series
print("Most frequent value of horsepower:", mode_value)


Most frequent value of horsepower: 152.0


In [31]:
mode_value = df['horsepower'].mode()[0]  # mode() returns a Series
print("Most frequent value of horsepower:", mode_value)


0    152.0
Name: horsepower, dtype: float64

In [37]:
# Fill Null Values of Horse power

df['horsepower'].fillna(mode_value, inplace=True)

/tmp/ipykernel_15918/654546431.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(mode_value, inplace=True)


In [38]:
# Find median again after filling

median_after = df['horsepower'].median()
print("Median after filling missing values:", median_after)


Median after filling missing values: 152.0


#### Q7. Sum of weights

- Select all the cars from Asia
- Select only columns vehicle_weight and model_year
- Select the first 7 values
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the sum of all the elements of the result?


In [41]:
# Sellecting cars from Asia
df_asia = df[df['origin'] == 'Asia']
df_asia.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [42]:
# Select only columns vehicle_weight and model_year

df_asia_sel = df_asia[['vehicle_weight', 'model_year']]
df_asia_sel.head()


vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [44]:
df_asia_sel7 = df_asia_sel.head(7)
df_asia_sel7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [46]:
X = df_asia_sel7.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [47]:
# matrix-matrix multiplication between the transpose of X and X.

XTX = X.T @ X  # or np.dot(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [51]:
# Invert XTX

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [53]:
# Creating an array
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [55]:
# Compute w

w = XTX_inv @ X.T @ y
w

array([0.01386421, 0.5049067 ])

In [56]:
# Sum all elements of w

sum_w = w.sum()
print("Sum of all elements in w:", sum_w)


Sum of all elements in w: 0.5187709081074016
