## Machine Learning Zoomcamp

## 1.7 Introduction to NumPy

Plan 
-  Creating arrays
-  Random generated arrays
-  Element wise operations
    - Comparsion Operations
    - Logical Operations
- Summarizing Operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays

In [30]:
# Crating an array with zeros

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
# Creating an array with ones

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
# An array of the same numbers

np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
# Assignig values to an array

a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
a[2]

np.int64(3)

In [33]:
# Changing the value in position 3

a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [12]:
# Crating a range

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Starting from 3

np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:

np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimenstional array

In [18]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
n = np.array([
    [1, 2, 3],
    [5, 6, 7],
    [8, 9, 10]
])

In [26]:
n

array([[ 1, 20,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [27]:
n[0, 1] = 20

In [28]:
n

array([[ 1, 20,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [29]:
n[0]

array([ 1, 20,  3])

In [34]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 5,  6,  7],
       [ 1,  1,  1]])

In [35]:
n[:, 1]

array([20,  6,  1])

In [36]:
# Return all rows

n[:]

array([[ 1, 20,  3],
       [ 5,  6,  7],
       [ 1,  1,  1]])

In [37]:
n[:, 2] = [0, 1, 2]

n

array([[ 1, 20,  0],
       [ 5,  6,  1],
       [ 1,  1,  2]])

## Random generated 

In [39]:
np.random.rand(5, 2)

array([[0.81435473, 0.85536447],
       [0.03365508, 0.33144279],
       [0.18471259, 0.8253463 ],
       [0.2591922 , 0.88330389],
       [0.9581904 , 0.8410243 ]])

In [42]:
np.random.seed(2)

np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [43]:
np.random.seed(2)

np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [46]:
np.random.seed(2)

np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise Operations

In [47]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [48]:
a + 1

array([1, 2, 3, 4, 5])

In [49]:
a * 2

array([0, 2, 4, 6, 8])

In [53]:
b = 10 + (a * 2) ** 2 /100
b

array([10.  , 10.04, 10.16, 10.36, 10.64])

In [54]:
a + b

array([10.  , 11.04, 12.16, 13.36, 14.64])

## Comparison Operations

In [55]:
a > b

array([False, False, False, False, False])